version: 30.0.50-{build}
shallow_clone: true

environment:
  matrix:
  - FLAVOR: mingw64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  # running under CI
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
  - 'echo End install at: & time /t'

build_script:
  - 'pushd %APPVEYOR_BUILD_FOLDER%'
  - 'bash -lc "pwd"'
  - 'bash -lc "pushd /c/projects/emacs-w64 && ./autogen.sh"'
  - 'bash -lc "pushd /c/projects/emacs-w64 && ./configure --prefix=/c/emacs-dist --with-modules --with-tree-sitter --with-native-compilation --with-gnutls --without-dbus --without-pop CFLAGS=-O2"'
  - 'bash -lc "pushd /c/projects/emacs-w64 && make bootstrap && make install"'

after_build:
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\pack.bat'

artifacts:
  - path: '*.zip'
