name: Emacs MSYS2 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: 'configure git core.autocrlf'
      shell: cmd
      run: git config --global core.autocrlf false
    - name: 'configure git core.eol'
      shell: cmd
      run: git config --global core.eol lf

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 3

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: git zip base-devel mingw-w64-x86_64-autotools mingw-w64-x86_64-toolchain mingw-w64-x86_64-xpm-nox mingw-w64-x86_64-libtiff mingw-w64-x86_64-giflib mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-librsvg mingw-w64-x86_64-libwebp mingw-w64-x86_64-lcms2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-jansson mingw-w64-x86_64-libgccjit mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-zlib mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-libtree-sitter mingw-w64-x86_64-sqlite3

    - name: '🚧 Build and Pack'
      run: |
        ./autogen.sh
        ./configure --prefix=/c/emacs-`git rev-parse --short HEAD~2` --with-modules --with-tree-sitter --with-native-compilation --with-gnutls --without-dbus --without-pop CFLAGS="-O2 -fno-optimize-sibling-calls"
        make
        make install
        git log -m --abbrev-commit --date=relative -3
        zip -r /c/emacs-`git rev-parse --short HEAD~2`.zip /c/emacs-`git rev-parse --short HEAD~2`/

    # - name: 'Pack'
    #   run: |
    #     zip -r /c/emacs-`git rev-parse --short HEAD~2`.zip /c/emacs-dist/*

    - name: 'Upload'
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sys }}-packages
        path: C:/emacs*.zip
        if-no-files-found: ignore
